name: Sync To Gitee
on:
  push:
    branches: [ master ]
jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        env:
          API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
          APPLICATION_ID: ${{ secrets.ALGOLIA_APPLICATION_ID }}
        with:
          node-version: '14.x'
      - name: Test Build
        run: |
          cd tDCS
          if [ -e yarn.lock ]; then
          yarn install --frozen-lockfile
          elif [ -e package-lock.json ]; then
          npm ci
          else
          npm i
          fi
          yarn build
          docker run -i -e "APPLICATION_ID=${APPLICATION_ID}" -e "APP_KEY=${APP_KEY}" -e "CONFIG=$(cat ../scrapy.json | jq -r tostring)" algolia/docsearch-scraper:v1.16.0
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_ACTION_PRV }}
        with:
          source-repo: "git@github.com:Entertech/tDCS-Documents.git"
          destination-repo: "git@gitee.com:Lockeysama/tDCS-Documents.git"